name: eda
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.8
  - mlflow=2.0.1
  - jupyter
  - jupyterlab=3.0.12
  - numpy=1.20
  - pandas=1.2.3
  - pip=20.3.3
  - ydata-profiling
  - pyarrow=2.0
  - pip:
      - wandb==0.13.4